# ~/.config/hypr/hyprpaper.conf

# Disable the hyprland splash text
splash = false

# may be some other time
ipc = false

# Set the wallpaper
wallpaper {
    monitor = 
    path = ~/.config/hypr/wallpapers/lake.jpeg
    fit_mode = cover
}